name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Install gomobile
        run: |
          go install github.com/sagernet/gomobile@latest
          gomobile init

      - name: Build Android library
        env:
          CGO_LDFLAGS: "-Wl,-z,max-page-size=16384"
        run: |
          gomobile bind -v -androidapi 21 -trimpath -tags='disable_debug' -ldflags='-s -w -buildid=' .
          rm -r libcore-sources.jar

      - name: Upload libcore.aar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: libcore
          path: libcore.aar
